{
  "home": "Home",
  "movies": "Movies",
  "recommended": "Recommended",
  "news": "News",
  "about": "About",
  "contacts": "Contacts",
  "quiz": "Quiz",
  "signIn": "Sign In",
  "signOut": "Sign Out",
  "searchMovies": "Search movies...",
  "profile": "Your Profile",
  "searchResultsFor": "Search results for «{{query}}»",
  "allMovies": "All Movies",
  "allGenres": "All Genres",
  "ratings": "Ratings",
  "comingSoon": "Coming Soon",
  "search": "Search",
  "hide": "Hide",
  "filters": "Filters",
  "genres": "Genres",
  "yearRange": "Year Range",
  "minRating": "Min. Rating",
  "sortBy": "Sort By",
  "apply": "Apply",
  "reset": "Reset",
  "searchingForMovies": "Searching for movies...",
  "noMoviesFound": "No movies found matching your search criteria.",
  "resetSearch": "Reset Search",
  "loadingCarousel": "Loading carousel...",
  "errorLoadingCarousel": "Error loading carousel",
  "loadingNews": "Loading news...",
  "errorFetchingNews": "Error fetching news",
  "noNewsToDisplay": "No news to display.",
  "loadingMovies": "Loading movies...",
  "error": "Error",
  "noMoviesToDisplayInThisSection": "No movies to display in this section.",
  "navigation": "Navigation",
  "legal": "Legal",
  "connect": "Connect",
  "termsOfService": "Terms of Service",
  "privacyPolicy": "Privacy Policy",
  "cookiePolicy": "Cookie Policy",
  "aboutMovieQ": "About MovieQ",
  "ourMission": "Our Mission",
  "aboutMissionText": "MovieQ is a user-friendly movie review platform designed for film enthusiasts. Our goal is to create a space where you can discover, discuss, and organize your cinematic journey.",
  "whatWeOffer": "What We Offer",
  "aboutOffer1": "Stay updated on both new releases and classic films.",
  "aboutOffer2": "Rate movies and read reviews from fellow users.",
  "aboutOffer3": "Leave your own comments and engage in discussions.",
  "aboutOffer4": "Build and manage your personal watchlist.",
  "aboutOffer5": "Mark films you've already seen.",
  "aboutOffer6": "Curate a list of your favorite movies.",
  "aboutOffer7": "Follow the latest movie news and developments.",
  "aboutOffer8": "Easily find films using our advanced filtering system.",
  "aboutEnjoyTool": "If you're a movie lover, we believe you'll find MovieQ a valuable and enjoyable tool!",
  "projectDetails": "Project Details",
  "category": "Category:",
  "categoryValue": "Film Platform & Community",
  "inspiredBy": "Inspired By:",
  "website": "Website:",
  "createdBy": "Created By",
  "sduName": "Suleyman Demirel University",
  "contactUs": "Contact Us",
  "contactIntro": "Have questions, suggestions, or feedback? We'd love to hear from you! Fill out the form below, and we'll get back to you as soon as possible.",
  "contactThankYou": "Thank you for your message! We'll be in touch soon.",
  "name": "Name",
  "yourName": "Your Name",
  "email": "Email",
  "yourEmail": "your.email@example.com",
  "subject": "Subject",
  "subjectPlaceholder": "What is this regarding?",
  "message": "Message",
  "messagePlaceholder": "Your detailed message...",
  "sending": "Sending...",
  "sendMessage": "Send Message",
  "otherWaysToReachUs": "Other Ways to Reach Us",
  "generalInquiries": "For general inquiries, you can also reach out to us at:",
  "contactEmail": "movieq3231@gmail.com",
  "welcomeBack": "Welcome back!",
  "emailOrUsername": "Email or Username",
  "enterEmailOrUsername": "Enter your email or username",
  "password": "Password",
  "enterPassword": "Enter your password",
  "rememberMe": "Remember me",
  "forgotPassword": "Forgot password?",
  "dontHaveAccount": "Don't have an account?",
  "createOne": "Create one",
  "createAccount": "Create Account",
  "joinToday": "Join today and start your movie journey!",
  "enterEmail": "Enter your email",
  "username": "Username",
  "chooseUsername": "Choose a username",
  "createPassword": "Create a password",
  "confirmPassword": "Confirm Password",
  "confirmPasswordPlaceholder": "Re-enter your password",
  "register": "Register",
  "alreadyHaveAccount": "Already have an account?",
  "resetPassword": "Reset Password",
  "enterEmailToReset": "Enter your email to reset your password.",
  "enterEmailAddress": "Enter your email address",
  "backToSignIn": "Back to Sign In",
  "editProfile": "Edit Profile",
  "myLists": "My Lists",
  "settings": "Settings",
  "favorites": "Favorites",
  "watchlist": "Watchlist",
  "noBioYet": "No bio yet.",
  "saveChanges": "Save Changes",
  "changePhoto": "Change Photo",
  "bio": "Bio",
  "bioPlaceholder": "Tell us about yourself...",
  "bioHelp": "Share a little about yourself, your favorite movies, or your interests.",
  "changeProfilePicture": "Change Profile Picture",
  "enterImageUrl": "Enter an image URL to set as your new profile picture.",
  "imageUrl": "Image URL",
  "preview": "Preview:",
  "cancel": "Cancel",
  "save": "Save",
  "backToNews": "Back to News",
  "loadingArticle": "Loading article...",
  "newsArticleNotFound": "News article not found.",
  "errorFetchingArticle": "Error fetching article.",
  "by": "by",
  "relatedMovies": "Related Movies",
  "popularCategories": "Popular Categories",
  "tvShows": "TV Shows",
  "streaming": "Streaming",
  "reviews": "Reviews",
  "getFilmUpdates": "Get Film Updates",
  "subscribeNewsletter": "Subscribe to our newsletter for the latest movie news, reviews, and exclusive content.",
  "yourEmailAddress": "Your email address",
  "subscribe": "Subscribe",
  "moreNews": "More News",
  "noNewsArticles": "No news articles to display.",
  "shareThisArticle": "Share this article",
  "twitter": "Twitter",
  "facebook": "Facebook",
  "copyLink": "Copy Link",
  "discoverMovies": "Discover Movies",
  "findNextFavorite": "Find your next favorite film",
  "randomGems": "Random Gems",
  "loadingOtherSections": "Loading other sections...",
  "noMoviesToDisplayFor": "No movies to display for",
  "recMovieGridTitle": "Recommended Movies",
  "discoverYourMoviePersonality": "Discover your movie personality",
  "yourMoviePreferences": "Your Movie Preferences",
  "restartQuiz": "Restart Quiz",
  "selectAllThatApply": "Select all that apply",
  "selectOneOption": "Select one option",
  "previous": "Previous",
  "next": "Next",
  "seeResults": "See Results",
  "releaseDate": "Release Date:",
  "duration": "Duration:",
  "director": "Director(s):",
  "starring": "Starring:",
  "plotSummary": "Plot Summary",
  "favorite": "Favorite",
  "favorited": "Favorited",
  "watched": "Watched",
  "addToFavorites": "Add to favorites",
  "removeFromFavorites": "Remove from favorites",
  "addToWatchlist": "Add to watchlist",
  "removeFromWatchlist": "Remove from watchlist",
  "markAsWatched": "Mark as watched",
  "markAsUnwatched": "Mark as unwatched",
  "loginToAddFavorites": "Please log in to add to favorites",
  "loginToAddWatchlist": "Please log in to add to watchlist",
  "loginToMarkWatched": "Please log in to mark as watched",
  "loadingMovieDetails": "Loading movie details...",
  "errorLoadingMovie": "Error Loading Movie",
  "retry": "Retry",
  "returnToHome": "Return to Home",
  "movieNotFound": "Movie Not Found",
  "movieNotLoaded": "The requested movie could not be loaded.",
  "language": "Language:",
  "genresLabel": "Genres:",
  "anyGenre": "Any genre",
  "from": "From",
  "to": "to",
  "min": "min",
  "loading": "Loading...",
  "personNotFound": "Person not found.",
  "born": "Born",
  "biography": "Biography",
  "noBiographyAvailable": "No biography available for {{name}}.",
  "asActor": "As Actor",
  "asDirector": "As Director",
  "loadMore": "Load More",
  "latestMovies": "Latest Movies",
  "popularMovies": "Popular Movies",
  "mostRated": "Most Rated",
  "latestNews": "Latest News",
  "notAvailable": "N/A",
  "unknown": "Unknown",
  "noImage": "No Image",
  "noPoster": "No Poster",
  "personIdentifierMissing": "Person identifier is missing.",
  "failedToLoadPersonDetails": "Failed to load person details.",
  "pageNotFound": "Page Not Found",
  "pageNotFoundMessage": "The page you're looking for doesn't exist or has been moved.",
  "goBack": "Go Back",
  "goHome": "Go Home",
  "requestedMovieCouldNotBeLoaded": "The requested movie could not be loaded.",
  "movieQ": "MovieQ",
  "trailer": "Trailer",
  "similarMovies": "Similar Movies",
  "comments": "Comments",
  "commentingAs": "Commenting as",
  "submitComment": "Submit Comment",
  "pleaseLogInToPostAComment": "Please log in to post a comment",
  "loadingComments": "Loading comments...",
  "noCommentsYetBeTheFirstToComment": "No comments yet. Be the first to comment.",
  "pleaseLogInToAddToFavorites": "Please log in to add to favorites",
  "pleaseLogInToAddToWatchlist": "Please log in to add to watchlist",
  "pleaseLogInToMarkAsWatched": "Please log in to mark as watched",
  "dateNotAvailable": "Date not available",
  "newsIdMissing": "News ID is missing.",
  "unknownErrorFetchingArticle": "An unknown error occurred while fetching the article.",
  "footerTagline": "The social platform for sharing your taste in movie.",
  "socialXAlt": "X logo",
  "socialFacebookAlt": "Facebook logo",
  "socialInstagramAlt": "Instagram logo",
  "footerBottom": "© {{year}} MovieQ. All rights reserved.",
  "security": "Security",
  "dangerZone": "Danger Zone",
  "changePassword": "Change Password",
  "currentPassword": "Current Password",
  "newPassword": "New Password",
  "passwordMinLengthHelp": "Password must be at least 6 characters long",
  "confirmNewPassword": "Confirm New Password",
  "updatePassword": "Update Password",
  "securitySettings": "Security Settings",
  "secondaryEmailAddress": "Secondary Email Address",
  "enterBackupEmail": "Enter a backup email address",
  "secondaryEmailHelp": "This email will be used for account recovery and important security notifications",
  "enterCurrentPasswordToConfirm": "Enter your current password to confirm changes",
  "updateSecuritySettings": "Update Security Settings",
  "deleteAccountWarning": "Once you delete your account, there is no going back. Please be certain.",
  "deleteMyAccount": "Delete My Account",
  "deleteAccount": "Delete Account",
  "deleteAccountModalText": "This action is irreversible. To confirm, please type \"{{username}}\" in the box below.",
  "confirmYourUsername": "Confirm your username",
  "removing": "Removing...",
  "remove": "Remove",
  "loadingYourMovies": "Loading your movies...",
  "noFavoriteMoviesYet": "No favorite movies yet",
  "noWatchedMoviesYet": "No watched movies yet",
  "yourWatchlistIsEmpty": "Your watchlist is empty",
  "noChangesToSave": "No changes to save.",
  "profileUpdatedSuccessfully": "Profile updated successfully!",
  "failedToUpdateProfile": "Failed to update profile.",
  "userProfilePictureAlt": "{{username}}'s profile",
  "any": "Any",
  "ratingHighToLow": "Rating (High to Low)",
  "ratingLowToHigh": "Rating (Low to High)",
  "popularityMost": "Popularity (Most)",
  "titleAZ": "Title (A-Z)",
  "titleZA": "Title (Z-A)",
  "yearNewest": "Year (Newest)",
  "yearOldest": "Year (Oldest)",
  "searchByTitle": "Search by title...",
  "yearExample": "Year (e.g., 2023)",
  "minRatingRange": "Min Rating (1-10)",
  "applyFilters": "Apply Filters",
  "failedToFetchMovies": "Failed to fetch movies.",
  "noMoviesFoundMatchingCriteria": "No movies found matching your criteria."
}
